version: '3.4'
services:
  db:
    image: paulormoj/mysql
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    build:
        context: .
        dockerfile: Dockerfile
    environment:
      MYSQL_DATABASE: 'test'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'admin'
      MYSQL_ROOT_PASSWORD: 'admin'
    ports:
      - '3308:3306'
    networks:
      - network
  rest-jokenpo:
    image: paulormoj/rest-jokenpo
    restart: always
    build: ./jokenpo
    working_dir: /jokenpo
    environment:
      TZ: America/Sao_Paulo
      SPRING_BOOT_ENVIROMENT: Production
    volumes:
      - ./jokenpo:/jokenpo
      - ~/.m2:/root/.m2
    ports:
      - "8080:8080"
    command: mvn clean spring-boot:run
    links:
      - db
    depends_on:
      - db
    networks:
      - network
networks:
  network:
      driver: bridge